language: java
flows:
    reusable_example:
        - shell: echo "Called from the reusable process"
        - parallel:
            - shell: echo "123"
            - shell: echo "234"
            - shell: echo "456"
    master:
        - shell: echo "Hello world!"
        - parallel:
            - shell: echo "A"
            - shell: echo "B"
        - call: reusable_example
