language: java
envs:
    example_env:
        - hello_string: Hello!
flows:
    reusable_example:
        - shell: echo "Called from the reusable process"
        - parallel:
            - shell: sleep 5
            - shell: sleep 5
            - shell: sleep 5

    simple:
        - parallel:
          - shell: sleep 5
          - shell: sleep 5

    nested_call:
        - parallel:
          - shell: sleep 5
          - call: simple

    nested:
        - parallel:
          - shell: sleep 5
          - parallel:
            - shell: sleep 5
            - shell: sleep 5

    deep_nested:
        - parallel:
            - shell: sleep 5
            - parallel:
              - shell: sleep 5
              - parallel:
                - shell: sleep 5
                - shell: sleep 5

     example_with_vars:
        - shell: echo #{hello_string}

    master:
        - shell: echo "Hello world!"
        - call: example_with_vars
