language: java
flows:
    reusable_example:
        - shell: echo "Called from the reusable process"
        - parallel:
            - shell: sleep 5
            - shell: sleep 5
            - shell: sleep 5

    nested:
        - parallel:
          - shell: sleep 5
          - parallel:
            - shell: sleep 5
            - shell: sleep 5

    deep_nested:
        - parallel:
            - shell: sleep 5
            - parallel:
              - shell: sleep 5
              - parallel:
                - shell: sleep 5
                - shell: sleep 5

    master:
        - shell: echo "Hello world!"
        - call: nested
