language: java
flows:
    reusable_example:
        - shell: echo "Called from the reusable process"
        - parallel:
            - shell: sleep 5
            - shell: sleep 5
            - shell: sleep 5
    master:
        - shell: echo "Hello world!"
        - parallel:
            - shell: sleep 5
            - shell: sleep 5
        - call: reusable_example
