language: java
flows:
    reusable_example:
        - shell: echo "Called from the reusable process"
        - parallel:
            - shell: sleep 5000 
            - shell: sleep 5000
            - shell: sleep 5000
    master:
        - shell: echo "Hello world!"
        - parallel:
            - shell: sleep 5000
            - shell: sleep 5000
        - call: reusable_example
